spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.43.104:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 3edc$RFV

logging:
  level:
    root: info
    com.zx: debug
  file:
    name: log/blog-dev.log

server:
  port: 8081

